dist: trusty
sudo: required
language: cpp
compiler: gcc-9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - export CC=gcc-9
    - export CXX=g++-9
    - gcc --version
    - g++ --version
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - cd external/open62541


    # Replace <user> and <token> with your GitHub username and access token respectively
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake .. -DCMAKE_INSTALL_PREFIX=/home/travis/install/open62541 -DUA_BUILD_TOOLS=ON -DUA_ENABLE_DISCOVERY_MULTICAST=ON -DUA_ENABLE_HARDENING=ON -DUA_ENABLE_NODESET_COMPILER_DESCRIPTIONS=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_PUBSUB_ETH_UADP=ON -DUA_ENABLE_SUBSCRIPTIONS=ON -DUA_LOGLEVEL=300 -DUA_NAMESPACE_ZERO=FULL -DBUILD_SHARED_LIBS=TRUE -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=ON
  - make install -j2
  - cd ../../../
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - ./test/openPubSubTests
