dist: trusty
sudo: required
language: cpp
compiler: gcc-9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - export CC=gcc-9
    - export CXX=g++-9
    - gcc --version
    - g++ --version
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - cd open62541
    - git submodule update --init --recursive

    # Replace <user> and <token> with your GitHub username and access token respectively
script:
  - ls
  - mkdir build && cd build
  - cmake ..
  - cmake -DUA_ENABLE_DISCOVERY=ON -DUA_ENABLE_DISCOVERY_MULTICAST=ON -DUA_ENABLE_HARDENING=ON -DUA_ENABLE_METHODCALLS=ON -DUA_ENABLE_NODEMANAGEMENT=ON -DUA_ENABLE_PARSING=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_PUBSUB_ETH_UADP=ON -DUA_NAMESPACE_ZERO=FULL ../
  - sudo make install
  - cd ../../
  - cmake .
  - cmake --build . -- -j2

after_success:
  -  bash <(curl -s https://codecov.io/bash)
